spin_manifest_version = 2

[application]
name = "image-manipulation"
version = "0.1.0"
authors = ["Radu Matei <radu@fermyon.com>"]
description = "An example for Spin component dependencies"

[[trigger.http]]
route = "/rust/..."
component = "image-manipulation-http-rs"


[component.image-manipulation-http-rs]
source = "image-manipulation-http-rs/target/wasm32-wasi/release/image_manipulation_http_rs.wasm"
[component.image-manipulation-http-rs.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "image-manipulation-http-rs"
watch = ["src/**/*.rs", "Cargo.toml"]

[component.image-manipulation-http-rs.dependencies]
"component:image-manipulation-lib/image-manipulation" = { version = "^1.0.0", registry = "fermyon.com", package = "fermyon-experimental:image-manipulation-lib" }

[[trigger.http]]
route = "/api/ts/..."
component = "image-manipulation-http-ts"

[component.image-manipulation-http-ts]
source = "image-manipulation-http-ts/target/image-manipulation-http-ts.wasm"
allowed_outbound_hosts = []

[component.image-manipulation-http-ts.build]
command = "npm run build"
workdir = "image-manipulation-http-ts"

[component.image-manipulation-http-ts.dependencies]
"component:image-manipulation-lib/image-manipulation" = { version = "^1.0.0", registry = "fermyon.com", package = "fermyon-experimental:image-manipulation-lib" }
